version: '3.8'

networks:
  db_net:

services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    networks:
      - db_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
    environment:
      ADMINER_DESIGN: 'nette'
      ADMINER_PLUGINS: 'tables-filter tinymce'
    networks:
      - db_net